#!/usr/bin/env python3
import json
import pathlib
import sys


def format_float(value):
    formatted = "{:.6f}".format(value).rstrip("0").rstrip(".")
    if "." not in formatted:
        formatted += ".0"
    return f"{formatted}f"


def main():
    script_dir = pathlib.Path(__file__).resolve().parent
    settings_path = script_dir.parent / "data" / "user_settings.json"
    settings = {}
    if settings_path.exists():
        try:
            with open(settings_path, "r", encoding="utf-8") as inp:
                settings = json.load(inp)
        except Exception as exc:
            print(f"Warning: failed to load {settings_path}: {exc}", file=sys.stderr)

    field_specs = [
        ("movement_mm_per_pulse", "TEST_MM_PER_PULSE", 2.88, float),
        ("detection_ratio_threshold", "TEST_RATIO_THRESHOLD", 0.25, float),
        ("detection_hard_jam_mm", "TEST_HARD_JAM_MM", 5.0, float),
        ("detection_soft_jam_time_ms", "TEST_SOFT_JAM_TIME_MS", 10000, int),
        ("detection_hard_jam_time_ms", "TEST_HARD_JAM_TIME_MS", 5000, int),
        ("detection_grace_period_ms", "TEST_GRACE_PERIOD_MS", 500, int),
        ("tracking_window_ms", "TEST_TRACKING_WINDOW_MS", 3000, int),
    ]

    generated_path = script_dir / "generated_test_settings.h"
    lines = [
        "// This file is generated by generate_test_settings.py",
        "#ifndef TEST_GENERATED_SETTINGS_H",
        "#define TEST_GENERATED_SETTINGS_H",
        "",
    ]

    for key, macro, default_value, value_type in field_specs:
        value = settings.get(key, default_value)
        if value_type is float:
            try:
                numeric_value = float(value)
            except (TypeError, ValueError):
                numeric_value = float(default_value)
            macro_value = format_float(numeric_value)
        else:
            try:
                numeric_value = int(value)
            except (TypeError, ValueError):
                numeric_value = int(default_value)
            macro_value = str(numeric_value)
        lines.append(f"#define {macro} {macro_value}")

    # Always include the check interval and resume grace defaults
    lines.extend(
        [
            "",
            "#define TEST_CHECK_INTERVAL_MS 1000",
            "#define TEST_RESUME_GRACE_MIN_MOVEMENT_MM 1.0f",
            "",
            "#endif  // TEST_GENERATED_SETTINGS_H",
        ]
    )

    generated_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
